### ISSUE TITLE
English Documentation

### ISSUE THREAD

**Issue by maxgerhardt** [pikasTech/pikadoc#1]
All files in https://github.com/pikasTech/pikadoc/tree/main/docs/source seem to be in chinese, and while most of it is code and thus maybe understandable, the text is not. People would have to use Google Translate or DeepL. Maybe native english documentation can be written?

**Comment by pikasTech** [comment]
Yes, the translation is coming.

**Comment by pikasTech** [comment]
The preliminary translation is here:

https://pikadoc.readthedocs.io/en/latest/index.html

**Comment by maxgerhardt** [comment]
That's already a great start, where are the english source files for that? They don't seem to be in this repo.

**Comment by pikasTech** [comment]
> That's already a great start, where are the english source files for that? They don't seem to be in this repo.

the repo is here:

https://github.com/pikasTech/pikadoc-en
